### ISSUE TITLE
The Graphs and such don't pop up

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#107]
![Screen Shot 2021-03-28 at 1.15.58 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/c3215ca5-96ca-4775-b223-a53929f315ec)

**Comment by GriffGreen** [comment]
For https://params.tecommons.org/hatch

**Comment by marthendalnunes** [comment]
the migration to the droplet that @mendesfabio will probably improve it, but panel still need a few seconds when starting to load all components :c
