### ISSUE TITLE
Vote for My Params of the Broadway Musical Selection

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#110]
<h1>Parameters</h1>

| Parameters                           |      Values |
|:-------------------------------------|------------:|
| Target raise (wxDai)                 | 11851300.00 |
| Maximum raise (wxDai)                | 56890465.00 |
| Minimum raise (wxDai)                |    10000.00 |
| Impact hour slope (wxDai/IH)         |     1269.00 |
| Maximum impact hour rate (wxDai/IH)  |      352.00 |
| Hatch oracle ratio (wxDai/CSTK)      |       45.70 |
| Hatch period (days)                  |       30.00 |
| Hatch exchange rate (TESTTECH/wxDai) |    36431.00 |
| Hatch tribute (%)                    |        0.29 |
| Support required (%)                 |       70.00 |
| Minimum accepted quorum (%)          |       10.00 |
| Vote duration (days)                 |        5.00 |
| Vote buffer (hours)                  |       12.00 |
| Rage quit (hours)                    |        5.00 |
| Tollgate fee (wxDai)                 |     1520.00 |
            
<h1>Results</h1>

<p></p>

- It costs 1520 wxDAI to make a proposal

- Votes will be voted on for 5 days

- TECH token holders will have 5 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There can be a maximum of 730 votes per year.

- A proposal that passes can be executed 17 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 91399 wxDai to the Hatch

Play with my parameters [here](https://tec-hatch-demo.herokuapp.com/hatch?ihminr=10000&hs=1269&maxihr=352&ihtr=11851300&ihmaxr=56890465.99999999&hor=45.699999999999996&hpd=30&her=36431&ht=29&sr=70&maq=10&vdd=5&vbh=12&rqh=5&tfx=1520).

            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/7af8679f-8fdc-4963-afeb-62671df44b78)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/51c0a59b-33a2-4c76-92c9-9e559516f1cf)

**Comment by GriffGreen** [comment]
you are hilarious... LOL
