### ISSUE TITLE
Shawn's feedback

### ISSUE THREAD

**Issue by LinuxIsCool** [CommonsBuild/Token-Log-Hatch-Params#112]
95 million is high for max goal and target goal.
Step should probably be 50 thousand on those.

This doesn't quite seem right. Seems like the first three rows are not updating: 
![image](https://user-images.githubusercontent.com/31582215/112763024-98c88f80-8fb7-11eb-8403-c3d7ca615e3a.png)

These tables should have titles:
![image](https://user-images.githubusercontent.com/31582215/112763053-bc8bd580-8fb7-11eb-8a20-7288906aa4ef.png)

This should go to 24 hours (maybe 48? maybe 7*24?)
![image](https://user-images.githubusercontent.com/31582215/112763113-f6f57280-8fb7-11eb-8cd2-dc146a7e9611.png)

100 seems too high for a minimum
![image](https://user-images.githubusercontent.com/31582215/112763142-0bd20600-8fb8-11eb-84d8-4b313a9444a4.png)

TECH Hatch DAO parameters are not updating:
![image](https://user-images.githubusercontent.com/31582215/112763204-5ce1fa00-8fb8-11eb-8c2b-05fbfd206910.png)

**Comment by GriffGreen** [comment]
Sem and Adria beg us to keep a very high tollgate fee, please keep the min at 100
