### ISSUE TITLE
Dandelion Voting graph is not updating

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#120]
![Screen Shot 2021-03-28 at 2.40.39 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/3e3320b0-b817-4998-b74e-13a231004bee)

**Comment by marthendalnunes** [comment]
that is probably a bug on Heroku execution, after the migration to the droplet it will probably improve. I will close it by now since there is not in the current codebase we can do to fix this occasional error.
