### ISSUE TITLE
Add  new columns to the Impact Hour Results table and link it in the github output

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#123]
SEE COMMENTS BELOW

These Columns DO NOT need to be in the designer's Dashboard can show what it is showing now

The output should look like this:

https://docs.google.com/spreadsheets/d/1CuzHsKZYBYj8JUtVX_PvY8vv__uK9fCm-Dt9VHbKZ28/edit?usp=sharing

The Yellow Columns are static, and up to date, the Green columns are calculated based on user data.

Columns B and C are the Columns that people should be looking at... so I put them first... and then moved the new columns to the end cause they don't matter much... But are good for information...

**Comment by marthendalnunes** [comment]
Add comment in the output issue linking the url w/ the preset params

**Comment by GriffGreen** [comment]
And make these charts show up on the Design page

**Comment by GriffGreen** [comment]
"To see the value of your individual Impact Hours, [click here to go to the Hatch Config Dashboard with these parameters](link) and explore the Impact Hour Results table."
