### ISSUE TITLE
Include this gif meme above the Results header

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#127]
Keep it on the page all the time :-D

https://imgflip.com/gif/530whg

<img width="437" alt="Screen Shot 2021-03-28 at 6 45 53 PM" src="https://user-images.githubusercontent.com/14945613/112772342-85a5d600-9030-11eb-8dd6-60f44b32213d.png">

**Comment by marthendalnunes** [comment]
https://user-images.githubusercontent.com/18421017/113240429-17a51d00-9283-11eb-9f6c-d4f90b6b4b42.mov
