### ISSUE TITLE
GIF blocks results text

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/Token-Log-Hatch-Params#140]
The input-output GIF blocks the text generated when I click `see my results` It also overlaps a bit with the table to the left. 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/a5392639-c208-4093-90ad-0d216af8c1d6)

**Comment by divine-comedian** [comment]
Still hitting the same issue here @marthendalnunes - The image/text are overlapping 

![image](https://user-images.githubusercontent.com/67759413/114093824-94d72000-9889-11eb-9e58-a9e5b0650f37.png)

**Comment by mendesfabio** [comment]
Fixed #183.
