### ISSUE TITLE
Fix output table to percentage for redeemable tribute and cultural build tribute (*100)

### ISSUE THREAD

**Issue by marthendalnunes** [CommonsBuild/Token-Log-Hatch-Params#142]
![image](https://user-images.githubusercontent.com/18421017/113517756-5e7f6500-9558-11eb-9152-4d5db73f8c42.png)

**Comment by GriffGreen** [comment]
@marthendalnunes please also add (%) to the headers

**Comment by marthendalnunes** [comment]
fixed : ) 
![image](https://user-images.githubusercontent.com/18421017/113758896-cf568680-96ea-11eb-9410-414020d15493.png)
