### ISSUE TITLE
Change the meme for "IH rate is too low"

### ISSUE THREAD

**Issue by marthendalnunes** [CommonsBuild/Token-Log-Hatch-Params#144]
The current meme is politically charged... while hillarious, we don't need the drama here. @laurenluz meme below is great lets use that.

**Comment by marthendalnunes** [comment]
@GriffGreen what should be the IH rate threshold for this message?

**Comment by GriffGreen** [comment]
@marthendalnunes 

Min recommended IH Rate for Real Hatch Dash  = 5 wxDai/IH

Min recommended IH Rate for Test Hatch Dash  = 0.025 wxDai/IH

**Comment by GriffGreen** [comment]
Yeah I broke a rule and assigned all of you... We pick a meme once we have 5

We need a meme that pops up when people pick a low impact hour rate... 

A low impact hour rate would shaft all the people who put in a bunch of work to make this a reality... Favoring instead the people who are putting in money. 

What Meme do we want to use to alert people this is an issue? 

YOUR MEME 

VITOR'S CHOICE!

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/113741808-3f4f1780-96bf-11eb-9fbd-b357b74e4016.png)


https://imgflip.com/i/54l0iv
