### ISSUE TITLE
Update the video that was embedded that shows how to use the dashboard

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#148]
Griff will make it when we get stable

**Comment by GriffGreen** [comment]
We can add a youtube link video where the Impact hours were. :-D

**Comment by marthendalnunes** [comment]
I've already tested and it is pretty doable to embed a video on panel. Hint: https://panel.holoviz.org/reference/panes/Video.html

**Comment by kristoferlund** [comment]
I'll put this on hold until there is a video. @GriffGreen, ping me when there is one.
