### ISSUE TITLE
Get param doc option visible

### ISSUE THREAD

**Issue by LinuxIsCool** [CommonsBuild/Token-Log-Hatch-Params#15]
doc = "..."

**Comment by LinuxIsCool** [comment]
https://panel.holoviz.org/user_guide/Param.html

**Comment by GriffGreen** [comment]
Take the code from the documentation and try to get the doc screen to render

**Comment by LinuxIsCool** [comment]
Here is a video series that will help:

https://www.youtube.com/playlist?list=PLusWL9gf0FISmLiW2iPykEW2k8PUrlbyC

**Comment by marthendalnunes** [comment]
Closing because @mendesfabio got an awesome solution implemented on #179.
![YsbKHg1](https://user-images.githubusercontent.com/18421017/114091013-83dcdd80-988e-11eb-8bdf-2ab97ebfd6c1.gif)
