### ISSUE TITLE
Make every text block shorter and bullet point-ed

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#153]
<img width="1406" alt="Hatch Dash" src="https://user-images.githubusercontent.com/74842263/113519358-dd6ca180-9548-11eb-8354-cb06b79176d3.png">

If we are going to have sentences and links then we should shorten those or redo them completely and try to make them minimal.

**Comment by GriffGreen** [comment]
Yeah no one is going to read it... we should make it one sentence. It can be done after #166

**Comment by laurenluz** [comment]
There's a typo also, in the first one...

![image](https://user-images.githubusercontent.com/75490971/113738310-06fa0a00-96bc-11eb-9b0d-2b8b252bbb93.png)

**Comment by freedumbs00** [comment]
https://docs.google.com/document/d/15tZ7f17YdMTGrbFXQoMEiiPP3VCMTrkzH7dHLQriaU0/edit#

**Comment by freedumbs00** [comment]
That should do the trick

**Comment by GriffGreen** [comment]
Looks Great!!!

**Comment by GriffGreen** [comment]
related to #221

**Comment by mendesfabio** [comment]
@freedumbs00 I added the deep dive link to each icon, so the user can either mouse over the icon for a quick definition or click to go to TEC deep dive page about the param. Could you improve the following text by adding this info?

`To learn more about each parameter, mouse over the “?” for definitions, or see the Hatch Spec for a more thorough explanation.`

**Comment by GriffGreen** [comment]
@mendesfabio I added it and made a few more revisions

**Comment by mendesfabio** [comment]
@PabloCGL tackled this issue, changes are live at https://dev-tec-hatch-demo.herokuapp.com/hatch.
