### ISSUE TITLE
Can we update or improve the Impact Hours curve? Or delete it? 

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#154]
![Screen Shot 2021-04-04 at 1 43 12 PM](https://user-images.githubusercontent.com/74842263/113519785-c11e3400-954b-11eb-93dd-a2e8f4a54384.png)

**Comment by divine-comedian** [comment]
I'm agree with jake on this one, this graph doesn't make much sense to me and I mostly ignore it. 

If we want to show our current and historic impact hours for the TEC perhaps we can clean up the graph, get rid of the 3 line curve and just show vetical bar graphs for the historic/current count of cumulative impact hours. 

Right now there's a lot going on and not much explanation so we have to decide what's worth explaning, and remove the rest so its less confusing.

**Comment by freedumbs00** [comment]
Yeah..  The simpler the better and for the love of god get rid of the gifs

**Comment by GriffGreen** [comment]
I agree... lets get rid of the graph above.. it's pretty but unnecessary.

**Comment by marthendalnunes** [comment]
@mendesfabio we will need to update the html template and think on something to fill that space

**Comment by GriffGreen** [comment]
Could we put the Impact Hours Results up there?

Or the Error Memes?

**Comment by freedumbs00** [comment]
I don't think anything needs to be there

**Comment by mendesfabio** [comment]
@GriffGreen I think it would be against the user flow, users might not even see the memes if they appear at the beginning of the page. If needed, I would put some image, chart, etc, from the TEC Forum, the image could have a link to the forum as well.

**Comment by freedumbs00** [comment]
I like a TEC branding img.
