### ISSUE TITLE
Scaling doesn't adjust automatically for lower params

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/Token-Log-Hatch-Params#155]
This makes changes in the UI hard to perceive

**Comment by santteegt** [comment]
Currently, figures x-limits are hardcoded. Is it okay to make them dynamic or are these set by design (hatch vs test_hatch)?

**Comment by GriffGreen** [comment]
There are a lot of things that change when you have different targets, we made a test hatch dashboard for smaller amounts...
