### ISSUE TITLE
Update the Impact Hours to the predicted amounts

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#156]
![Screen Shot 2021-04-04 at 1 51 59 PM](https://user-images.githubusercontent.com/74842263/113519960-01ca7d00-954d-11eb-9e56-ea4397589a72.png)

They're pretty off right now and we could use the predictions on the spreadsheets.  They're already pretty close

Here are the Predicted IH: https://docs.google.com/spreadsheets/d/1CuzHsKZYBYj8JUtVX_PvY8vv__uK9fCm-Dt9VHbKZ28/edit#gid=1821832026

**Comment by GriffGreen** [comment]
Yes these desperately need to be updated
