### ISSUE TITLE
Make the pie charts larger and change cultural tribute to "Impact Hours"

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#157]

**Comment by laurenluz** [comment]
or at the very least make them all the same size 
![image](https://user-images.githubusercontent.com/75490971/113738727-5fc9a280-96bc-11eb-8f1a-eb30a0ab0cc0.png)

**Comment by GriffGreen** [comment]
The size was supposed to give the relative perspective... but maybe you are right @laurenluz we should remove that feature and focus on comparing the percentages.

What is interesting is the Cultural build tribute gets converted to a number that makes sense here ;-)
