### ISSUE TITLE
Make Tests for the Param Objects (ImpactHours, Hatch, DandelionVoting)

### ISSUE THREAD

**Issue by LinuxIsCool** [CommonsBuild/Token-Log-Hatch-Params#16]
Make test functions for the classes and their functions. Unit tests as similar to the commons simulator testing setup. Possibly integration tests as well.

**Comment by divine-comedian** [comment]
@LinuxIsCool @marthendalnunes   guysss.. Finally tests are running okay but would like some feedback on how I can write some more rigorous tests.. 

![image](https://user-images.githubusercontent.com/67759413/112373825-c6f85780-8cb7-11eb-9955-cae59ee5290f.png)
