### ISSUE TITLE
Section 2: Parameters Chart - may cause confusion

### ISSUE THREAD

**Issue by KZFlyer** [CommonsBuild/Token-Log-Hatch-Params#161]
Line chart updates, but parameters chart to the right does not update after running simulation, user must "view your results" before the data changes. Is it possible to hide that data until the results are run? 

The space could have a header something like "Your Final Hatch Results" and below it could instruct them to click view results.

![image](https://user-images.githubusercontent.com/39107717/113520328-4f041a00-9560-11eb-9a1a-fae2f64fb517.png)
![image](https://user-images.githubusercontent.com/39107717/113520340-588d8200-9560-11eb-9554-c01f011248dc.png)

**Comment by marthendalnunes** [comment]
@mendesfabio maybe changing that action button trigger might fix it

**Comment by GriffGreen** [comment]
Does the Action button trigger mean that when you run simulation it will update the results as well?
