### ISSUE TITLE
Allow user to enter number where there is a slider

### ISSUE THREAD

**Issue by KZFlyer** [CommonsBuild/Token-Log-Hatch-Params#163]
Some may have difficulty getting the value they want with the slider. Add the ability to enter the desired number or arrows, or both.

![image](https://user-images.githubusercontent.com/39107717/113521110-6a255880-9565-11eb-9c37-b312f88b8701.png)

![image](https://user-images.githubusercontent.com/39107717/113521092-5aa60f80-9565-11eb-9748-4b0ba1838ae5.png)

**Comment by marthendalnunes** [comment]
This issue will be closed because of #201
