### ISSUE TITLE
Create a meme for if people have both too low of an impact hour rate and too high of a cultural build tribute

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#169]
If people propose REAL BAD parameters... then they should get an extra funny meme... 

It's like they aren't even trying... or maybe... they are trying to create a really bad DAO... 

What Meme do we want to use for this?

YOUR MEME

VITOR'S CHOICE!

**Comment by GriffGreen** [comment]
Related to #144, #143

**Comment by divine-comedian** [comment]
@markoprljic

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/113764743-9c0afc00-96d8-11eb-81be-aee8a958251d.png)
https://imgflip.com/i/54lu62

![image](https://user-images.githubusercontent.com/75490971/113764798-ac22db80-96d8-11eb-8fa4-3d4a853e33ad.png)
https://imgflip.com/i/54lvlm

![image](https://user-images.githubusercontent.com/75490971/113764846-be047e80-96d8-11eb-8442-360cc7da6766.png)
https://imgflip.com/i/54lwd5

**Comment by divine-comedian** [comment]
Oooh those are good Lauren

**Comment by divine-comedian** [comment]
<a href="https://imgflip.com/i/54oyvr"><img src="https://i.imgflip.com/54oyvr.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>
https://imgflip.com/i/54oyvr
<a href="https://imgflip.com/i/54ozid"><img src="https://i.imgflip.com/54ozid.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>
https://imgflip.com/i/54ozid
<a href="https://imgflip.com/i/54p1y8"><img src="https://i.imgflip.com/54p1y8.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>
https://imgflip.com/i/54p1y8

**Comment by GriffGreen** [comment]
hahahahaah omfg so funny
