### ISSUE TITLE
Create a trigger condition for "IH rate is too low"

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#172]
copy the cultural build tribute trigger

**Comment by kristoferlund** [comment]
@GriffGreen what is the trigger point for "too low"? 

$10?

![image](https://user-images.githubusercontent.com/9698363/114002644-588dca80-985d-11eb-8636-c7ddaaf92e57.png)
https://i.imgflip.com/54tdpy.jpg

**Comment by kristoferlund** [comment]
Ah, found the trigger in #144, setting to 5.

**Comment by GriffGreen** [comment]
omg! @kristoferlund you are hilarious! But we can't use a politically charged meme!

**Comment by kristoferlund** [comment]
Ah, of course! I fix. Do we have an alternative meme?
