### ISSUE TITLE
Can only "run simulation" 2 (ish) times (or for some period of time) before having to refresh the simulator

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/Token-Log-Hatch-Params#173]
From feedback from @freedumbs00 ... on his computer he can only run 2 times. Griff was able to run 3 times. Mitch was able to run 5-6 times yesterday but some weeks ago was having the issue. Maybe it's time-dependent? OR could be different on different computers?

We should inform people that this is happening so they know that the dashboard still works, even if it looks like it's not. Or.... if we can, we could figure out why this is happening and fix the issue. 

Do you know about this @marthendalnunes

**Comment by marthendalnunes** [comment]
Hmmm, maybe this happens due to a server timeout, I'll dig into it. @mendesfabio any hint?

**Comment by mendesfabio** [comment]
You all could try it again and confirm it still happens? Asking this because I found and fixed a bug today that seems related to.

**Comment by freedumbs00** [comment]
I have been able to run multiple simulations with time variants and no problems.  I'm going close this issue
