### ISSUE TITLE
We need to do something about all this space

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#186]
![Screen Shot 2021-04-08 at 4 14 16 PM](https://user-images.githubusercontent.com/74842263/114103009-930b5d80-9885-11eb-911e-d9ce0d9eac3e.png)

**Comment by freedumbs00** [comment]
I'm pretty sure this is already an issue about using a logo or a meme?  or moving the Impact Hour Rate chart up?

**Comment by mendesfabio** [comment]
We'll add a video there, so I'm closing in favor of #148.
