### ISSUE TITLE
Add the output chart to the results

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#212]
Add this chart:

![Screen Shot 2021-04-18 at 1.41.39 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/5d55b817-5385-4075-8464-0f9ef4390645)

To the very bottom of the dashboard when someone clicks "See your results"

**Comment by marthendalnunes** [comment]
@mendesfabio the panel object is already done, we need only to add another space in the HTML I guess
