### ISSUE TITLE
Remove Cultural Build Tribute output completely

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#215]
People really want to understand it, and it becomes a blocker for using the dashboard, even changing the name might not be enough.

Having just Impact hour rate and Backer RageQuit % should be enough for people to design with

Remove it everywhere, including:
![Screen Shot 2021-04-18 at 2.16.01 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/7f2682aa-2013-47ce-bdbc-3fabd2644374)
![Screen Shot 2021-04-18 at 2.16.13 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/f777ea6c-a849-48b9-ad4a-58fc059955c2)
![Screen Shot 2021-04-18 at 2.19.20 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/eca716bd-109b-4548-9d88-660430153b92)

**Comment by marthendalnunes** [comment]
@GriffGreen do you think we will need it in the future? I think about just not showing it to the user, but maybe keeping it in the codebase (commented) for later use.
