### ISSUE TITLE
Why does the "Hatch Tribute" change in the pie charts?

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#217]
Shouldn't the "Hatch Tribute" % (soon to be called non-redeemable %) always be the same... sure the total AMOUNT might change but the % should be consistent ???

**Comment by santteegt** [comment]
After checking the code & formulas, seems reasonable that there's a slight difference (~1%) in the non-redeemable percentage value for different raise targets. With `hatch_tribute` being the only constant (C) and `impact_hour_rate` (V) depending on the raise amount (min, max, target), then:

```
cultural_tribute = min(raise_amount(V), impact_hour_rate(V) * total_impact_hours(C))
```

Thus:

```
non_redeemable_% = (raise_amount(V) - cultural_tribute(V)) * hatch_tribute(C)
```
