### ISSUE TITLE
Change the legend for the piecharts

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#218]
![Screen Shot 2021-04-18 at 2.28.43 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/0e786bf5-a7fb-4b66-ac8d-a97be12142d9)

Black = Non-redeemable
Yellow = Backers can RageQuit
Blue = Builders can RageQuit

Also... the math seems wrong... this might need to be corrected so the math matches the legend as well :-D

**Comment by marthendalnunes** [comment]
@GriffGreen can you explain the math error?

**Comment by GriffGreen** [comment]
The non-redeemable % changes... that doesnt make any sense...
