### ISSUE TITLE
Link to the tokenlog page 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/Token-Log-Hatch-Params#221]
An easy way to jump to all the submitted proposals on https://tokenlog.xyz/CommonsBuild/TEC-Hatch-Vote from this dashboard would be great.

**Comment by GriffGreen** [comment]
@freedumbs00 can we add it to the text at the top?

**Comment by freedumbs00** [comment]
I don't see why not as a hyper link

**Comment by mendesfabio** [comment]
closing in favor of #153 since Griff added a link to tokenlog there.
