### ISSUE TITLE
Frame the Impact hour rate and Backer's RageQuit % charts with the params that can adjust them and the run simulation button

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#223]
Frame the Impact hour rate and Backer's RageQuit % charts with the params that can adjust them and the run simulation button...

This means you should be able to see all of this in one screen... including the invisible button!

![Screen Shot 2021-04-18 at 6.31.21 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/66768980-f35e-42fc-adc3-f983e42e4ea1)

![Screen Shot 2021-04-18 at 6.31.11 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/e591a36e-590f-4a94-aa72-e32568593bc6)

![Screen Shot 2021-04-18 at 6.31.00 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/c9ee60b6-9da6-42a6-a6cc-71a9d9c6c33a)

**Comment by marthendalnunes** [comment]
@mendesfabio maybe change the html layout now that we removed the cultural build tribute chart
