### ISSUE TITLE
This spread is bad Idea because it will constantly need to be updated.  It creates confusion

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/Token-Log-Hatch-Params#226]
![Screen Shot 2021-04-19 at 9.43.58 PM.png](https://images.zenhubusercontent.com/5fb9b1cedcaf66207689f19b/8281b151-a28f-4a55-8347-d36e4854e2bd)

**Comment by freedumbs00** [comment]
People will also want to understand how Assumed impact hours are created or what is Min. Impact hours.   This only creates false paradigms and is misleading.  More importantly its propaganda.  @GriffGreen

**Comment by GriffGreen** [comment]
@freedumbs00 what about if it is just 5 columns and it explicitly calls out the amount of money that it would take to create the tokens (this is the impact hour rate * the # of IH) vs the amount of money that you can rage quit out as described in: 

https://github.com/CommonsBuild/Token-Log-Hatch-Params/issues/206

It is not propaganda, it is an engagement piece and also very relevant information to design around. These people will get: 
1. This number of tokens
2. which would have cost X
3. and will be ragequitable for Y

Then the chart also shows a range of TECH vs Cost Vs RageQuit Value which has its own unique value :-D
