### ISSUE TITLE
Improve the tool tip for the Membership ratio

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#239]
@liviade1 made a great point... we should tell people that everyone will have 1125 CSTK minimum in the tool tip

change:
The amount of wxDAI (wrapped xDAI) each CSTK Token holder is able to send to the Hatch per CSTK they have.

to:

Multiplied by CSTK score to create a wxDai Cap for every Trusted Seed Member. The min CSTK Score possible is 1125 CSTK so if the membership ratio is 10, every member can send at least 11,250 wxDai to the Hatch.

**Comment by GriffGreen** [comment]
Is that too long?

**Comment by divine-comedian** [comment]
https://github.com/CommonsBuild/Token-Log-Hatch-Params/issues/248 closed with this PR
