### ISSUE TITLE
Do QA on the Github outputs

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#241]
- [x] Put the params list at the end, 
- [x] link to fork the proposal at the beginning, h/t @liviade1 
- [x] put all the pictures second 
- [x] Figure out the best layout for the rest

**Comment by laurenluz** [comment]
Yeah I like Griff's suggestions and propose the following example flow:

BEGIN:

I designed an economy using the Hatch Dashboard. Think you can do better? Click *here* to fork my params.

**Results**
![image](https://user-images.githubusercontent.com/75490971/116005903-44203080-a5c6-11eb-8fd0-2d81e0536be2.png)

**Impact Hour Rate**
[Impact Hour Rate](https://github.com/CommonsSwarm/impact-hours-app) is the hourly wage of TECH tokens awarded to TEC Community members that contributed work hours before the Hatch.

![image](https://user-images.githubusercontent.com/75490971/116006791-07563880-a5ca-11eb-82f6-2f060e623192.png)

**Backer's Rage Quit**
Backer’s Rage Quit % is the % of funds invested that is redeemable by the Backers if they decide to “rage quit” and leave the Commons before the Hatch.

![image](https://user-images.githubusercontent.com/75490971/116006929-8d727f00-a5ca-11eb-98c2-eefd0651637b.png)

![image](https://user-images.githubusercontent.com/75490971/116006961-babf2d00-a5ca-11eb-8656-11387f2c6201.png)

**Redeem-ability of the DAO's wxDai**
The amount of the DAO’s wxDai that is redeemable by backers, by builders, and the amount that is [not redeemable](https://forum.tecommons.org/t/the-hatch-tl-dr/272) is represented in the following pie charts.

![image](https://user-images.githubusercontent.com/75490971/116007076-3a4cfc00-a5cb-11eb-9fbb-756027959ccb.png)

**Minimum Support and Quorum Accepted for Proposals to Pass**
[Minimum support](https://forum.tecommons.org/t/support-required-deep-dive/108) is the percentage of tokens used in the vote that must choose “yes” in order for a proposal to pass. [Minimum quorum](https://forum.tecommons.org/t/minimum-quorum-deep-dive/133) is the percentage of the total supply of tokens that must choose “yes” in order for a proposal to pass.

![image](https://user-images.githubusercontent.com/75490971/116007128-72ecd580-a5cb-11eb-9c2d-c1edd506a280.png)

**Summary Table**
![image](https://user-images.githubusercontent.com/75490971/116007434-fbb84100-a5cc-11eb-96df-40d206f7f4c1.png)

**My Parameters**
![image](https://user-images.githubusercontent.com/75490971/116007659-25259c80-a5ce-11eb-9924-81929a72503f.png)

**Comments**
![image](https://user-images.githubusercontent.com/75490971/116007447-0a9ef380-a5cd-11eb-9edf-68319fdfba48.png)

Thanks for reading! Improve upon these results by clicking *here* to fork my params.

END

**Comment by laurenluz** [comment]
@divine-comedian @GriffGreen want to review and if you like we can pass to Vitor or Fabio to implement the changes?

**Comment by GriffGreen** [comment]
This is Great!

I love the sentences above each chart!

Not sure about the opening sentences or the order tho... I'll try another one

**Comment by divine-comedian** [comment]
## This is my proposal forked from lauren's proposal.

BEGIN:

### I just designed a **DAO** using the Hatch Dashboard. Try and iterate on my design if you think you can do better:

## Results
![image](https://user-images.githubusercontent.com/75490971/116005903-44203080-a5c6-11eb-8fd0-2d81e0536be2.png)

### [Impact Hour Rate](https://github.com/CommonsSwarm/impact-hours-app) 
The hourly wage of TECH tokens awarded to TEC Community members that contributed work hours before the Hatch.

![image](https://user-images.githubusercontent.com/75490971/116006791-07563880-a5ca-11eb-82f6-2f060e623192.png)

### Backer's Rage Quit %
The percent of funds invested that is redeemable by the Backers if they decide to “rage quit” and leave the Commons before the Hatch.

![image](https://user-images.githubusercontent.com/75490971/116006929-8d727f00-a5ca-11eb-98c2-eefd0651637b.png)

![image](https://user-images.githubusercontent.com/75490971/116006961-babf2d00-a5ca-11eb-8656-11387f2c6201.png)

### Redeem-ability of the DAO's wxDai
The amount of the Hatch’s wxDai that is redeemable by backers or builders if they rage quit and the amount that is [not redeemable](https://forum.tecommons.org/t/the-hatch-tl-dr/272) is represented in the following pie charts.

![image](https://user-images.githubusercontent.com/75490971/116007076-3a4cfc00-a5cb-11eb-9fbb-756027959ccb.png)

### [Minimum support](https://forum.tecommons.org/t/support-required-deep-dive/108) and [Minimum quorum](https://forum.tecommons.org/t/minimum-quorum-deep-dive/133)
 The percentage of tokens used in the vote that must choose “yes” in order for a proposal to pass and the percentage of the total supply of tokens that must choose “yes” in order for a proposal to pass.

![image](https://user-images.githubusercontent.com/75490971/116007128-72ecd580-a5cb-11eb-9c2d-c1edd506a280.png)

### Summary Table
![image](https://user-images.githubusercontent.com/75490971/116007434-fbb84100-a5cc-11eb-96df-40d206f7f4c1.png)

### My Parameters
![image](https://user-images.githubusercontent.com/75490971/116007659-25259c80-a5ce-11eb-9924-81929a72503f.png)

### Comments
![image](https://user-images.githubusercontent.com/75490971/116007447-0a9ef380-a5cd-11eb-9edf-68319fdfba48.png)

### Improve upon these results by clicking *here* to fork my params.

END

**Comment by laurenluz** [comment]
@divine-comedian I like the updated text at the beginning and end, and the edits to make the defining intros a bit shorter.

However, I don't love the breakdown for minimum support/quorum. I think it is confusing to have the title as two things and then two definitions concatenated below. I think it's better to have it like "minimum quorum is THIS. minimum support is THIS"

**Comment by divine-comedian** [comment]
SUGGEST - 
### Minimum Support
The percentage of tokens used in the vote that must choose “yes” in order for a proposal to pass.
### Minimum Quorum
The percentage of the total supply of tokens that must choose “yes” in order for a proposal to pass.

Also to move the 'Results' text at the top to the bottom with the comments text so all text blocks are together.

**Comment by laurenluz** [comment]
Ok SO. Because we are limited by time and we can't live the dream, here is the best I can come up with, given the circumstances. Re-arranged the order based on the way results are currently being spat out. See below:

Also ... please include the title of the pie charts above the pie charts....  "Redeem-ability of the Dao's wxDai"

START:

### I just designed a **DAO** using the Hatch Configuration Dashboard. Try and iterate on my design if you think you can do better:

<h1>Results</h1>

![image](https://hcti.io/v1/image/8b32fd54-9a00-43c9-b732-07bbefccc7b8)

- [Impact Hour Rate](https://github.com/CommonsSwarm/impact-hours-app): the hourly wage of TECH tokens awarded to TEC Community members that contributed work hours before the Hatch.
- Backer's Rage Quit %: the percent of funds invested that is redeemable by the Backers if they decide to “rage quit” and leave the Commons before the Hatch.
- Redeem-ability of the DAO's wxDai: the amount of the Hatch’s wxDai that is redeemable by backers or builders if they rage quit and the amount that is [not redeemable](https://forum.tecommons.org/t/the-hatch-tl-dr/272) is represented in the following pie charts.
- [Minimum support](https://forum.tecommons.org/t/support-required-deep-dive/108): the percentage of tokens used in the vote that must choose “yes” in order for a proposal to pass.
- [Minimum quorum](https://forum.tecommons.org/t/minimum-quorum-deep-dive/133): the percentage of the total supply of tokens that must choose “yes” in order for a proposal to pass.

<h1>Summary Table</h1>

![image](https://hcti.io/v1/image/e8dca5ec-2f88-43a2-a141-013eb61f64af)

<h1>Explanation</h1>

- It costs 500.0 wxDai to make a proposal.

- Votes will be voted on for 3 days.

- TECH token holders will have 12 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 3 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 15 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 100000 wxDai to the Hatch.

<h1>Comments</h1>
 - This is where the comments go

<h1>My Parameters</h1>

| Parameters                          |           Values |
|:------------------------------------|-----------------:|
| Target raise (wxDai)                | 10,000,000.00    |
| Maximum raise (wxDai)               | 25,000,000.00    |
| Minimum raise (wxDai)               |  1,250,000.00    |
| Impact hour slope (wxDai/IH)        |           351.00 |
| Maximum impact hour rate (wxDai/IH) |           300.00 |
| Hatch oracle ratio (wxDai/CSTK)     |            50.00 |
| Hatch period (days)                 |            14.00 |
| Hatch exchange rate (TECH/wxDai)    |      1,000.00    |
| Hatch tribute (%)                   |            18.00 |
| Support required (%)                |            62.00 |
| Minimum accepted quorum (%)         |             8.00 |
| Vote duration (days)                |             3.00 |
| Vote buffer (hours)                 |             3.00 |
| Rage quit (hours)                   |            12.00 |
| Tollgate fee (wxDai)                |           500.00 |
           
### Improve upon these results by clicking <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351.0&maxihr=300.0&ihtr=10000000&ihmaxr=25000000&hor=50.0&hpd=14&her=1000.0&ht=18&sr=62&maq=8&vdd=3&vbh=3&rqh=12&tfx=500.0" target="_blank">here</a> to fork my params.

### To see the value of your individual Impact Hours, click <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351.0&maxihr=300.0&ihtr=10000000&ihmaxr=25000000&hor=50.0&hpd=14&her=1000.0&ht=18&sr=62&maq=8&vdd=3&vbh=3&rqh=12&tfx=500.0" target="_blank">here to go to the Hatch Config Dashboard with these parameters</a> and explore the Impact Hour Results table.

END

@divine-comedian @GriffGreen  - can you review?

**Comment by divine-comedian** [comment]
START:

### I just designed a **DAO** using the Hatch Configuration Dashboard. Try and iterate on my design if you think you can do better:

<h1>Results</h1>

![image](https://hcti.io/v1/image/8b32fd54-9a00-43c9-b732-07bbefccc7b8)
### Parameter References
- [Impact Hour Rate](https://github.com/CommonsSwarm/impact-hours-app): the hourly wage of TECH tokens awarded to TEC Community members that contributed work hours before the Hatch.
- Backer's Rage Quit %: the percent of funds invested that is redeemable by the Backers if they decide to “rage quit” and leave the Commons before the Hatch.
- Redeem-ability of the DAO's wxDai: the amount of the Hatch’s wxDai that is redeemable by backers or builders if they rage quit and the amount that is [not redeemable](https://forum.tecommons.org/t/the-hatch-tl-dr/272) is represented in the following pie charts.
- [Minimum Support](https://forum.tecommons.org/t/support-required-deep-dive/108): the percentage of tokens used in the vote that must choose “yes” in order for a proposal to pass.
- [Minimum Quorum](https://forum.tecommons.org/t/minimum-quorum-deep-dive/133): the percentage of the total supply of tokens that must choose “yes” in order for a proposal to pass.

<h1>Summary Table</h1>

![image](https://hcti.io/v1/image/e8dca5ec-2f88-43a2-a141-013eb61f64af)

<h1>Explanation</h1>

- It costs 500.0 wxDai to make a proposal.

- Votes will be voted on for 3 days.

- TECH token holders will have 12 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 3 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 15 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 100000 wxDai to the Hatch.

<h1>Comments</h1>
 - This is where the comments go

<h1>My Parameters</h1>

| Parameters                          |           Values |
|:------------------------------------|-----------------:|
| Target raise (wxDai)                | 10,000,000.00    |
| Maximum raise (wxDai)               | 25,000,000.00    |
| Minimum raise (wxDai)               |  1,250,000.00    |
| Impact hour slope (wxDai/IH)        |           351.00 |
| Maximum impact hour rate (wxDai/IH) |           300.00 |
| Hatch oracle ratio (wxDai/CSTK)     |            50.00 |
| Hatch period (days)                 |            14.00 |
| Hatch exchange rate (TECH/wxDai)    |      1,000.00    |
| Hatch tribute (%)                   |            18.00 |
| Support required (%)                |            62.00 |
| Minimum accepted quorum (%)         |             8.00 |
| Vote duration (days)                |             3.00 |
| Vote buffer (hours)                 |             3.00 |
| Rage quit (hours)                   |            12.00 |
| Tollgate fee (wxDai)                |           500.00 |
           
### Improve upon these results by clicking <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351.0&maxihr=300.0&ihtr=10000000&ihmaxr=25000000&hor=50.0&hpd=14&her=1000.0&ht=18&sr=62&maq=8&vdd=3&vbh=3&rqh=12&tfx=500.0" target="_blank">here</a> to fork my params.

### To see the value of your individual Impact Hours, click <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351.0&maxihr=300.0&ihtr=10000000&ihmaxr=25000000&hor=50.0&hpd=14&her=1000.0&ht=18&sr=62&maq=8&vdd=3&vbh=3&rqh=12&tfx=500.0" target="_blank">here to go to the Hatch Config Dashboard with these parameters</a> and explore the Impact Hour Results table.

END

Just added a little header for the parameter references so they don't get lost in the melee. Capitalized some parameter names.

Looks great! :+1:

**Comment by GriffGreen** [comment]
Love what Mitch and Lauren came up with. There were some changes in our Sunday call so I updated this to match:

It should my comment below:

**Comment by GriffGreen** [comment]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=100000&tgihr=150&maxihr=500&ihtr=2500000&ihmaxr=50000000&hor=10&hpd=15&her=10000&ht=5&sr=60&maq=2&vdd=3&vbh=8&rqh=1&tfx=1000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

<a href="https://imgflip.com/i/57zyrl"><img src="https://i.imgflip.com/57zyrl.jpg" title="made at imgflip.com"/></a>
        
<h1>Graphical Summary</h1>

![image](https://hcti.io/v1/image/763a4cb9-dbf9-4dbb-a300-590e6da71573)
<h2>Graph Descriptions</h2>

- Top Left, [Impact Hour Rate vs wxDai Collected in Hatch](https://github.com/CommonsSwarm/impact-hours-app): The Impact Hour Rate determines Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch, determined by my Hatch Parameters 
- Top Right, Proposal Acceptance Criteria: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given my chosen [Support Required](https://forum.tecommons.org/t/support-required-deep-dive/108) & [Minimum Quorum](https://forum.tecommons.org/t/minimum-quorum-deep-dive/133).
- Bottom Left, Backer's Rage Quit % vs wxDai Collected in Hatch: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.  
- Bottom Right, Redeem-ability of the DAO's wxDai: Who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some of it can be withdrawn if token holders Ragequit. The pie charts show how this shakes out for my parameter choices at the different goals.


<h1>Simulated Outcomes</h1>

![image](https://hcti.io/v1/image/93fc11ce-d81a-404e-9406-3620313e15a6)


<h2>Hatch Strategy</h2>

<p>To use the defaults... Technocracy for the win</p>
            

<h2>DAO Strategy</h2>

<p>To use the defaults... Technocracy for the win</p>
            <h1>Summary</h1>



 <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 15 days.

- The target goal will be 2500000 wxDai, with a minimum of 100000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 50000000 wxDai.

- Backers will need to send in 0.0001 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 60% support, and a minimum of 2% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 1 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.


Iterate on my parameters <a href="https://params.tecommons.org/hatch?ihminr=100000&tgihr=150&maxihr=500&ihtr=2500000&ihmaxr=50000000&hor=10&hpd=15&her=10000&ht=5&sr=60&maq=2&vdd=3&vbh=8&rqh=1&tfx=1000" target="_blank">here</a>.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=100000&tgihr=150&maxihr=500&ihtr=2500000&ihmaxr=50000000&hor=10&hpd=15&her=10000&ht=5&sr=60&maq=2&vdd=3&vbh=8&rqh=1&tfx=1000" target="_blank">here, just check out the Impact Hour Results table.
            



<h1>My Hatch Configuration</h1>

| Parameter                                 |   Value |
|:-------------------------------------------|---------:|
| Minimum Goal (wxDai)                      |   100000 |
| Maximum Goal (wxDai)                      | 50000000 |
| Target Goal (wxDai)                       |  2500000 |
| Impact Hour Rate at Target Goal (wxDai/IH) |      150 |
| Impact Hour Rate at Infinity (wxDai/IH)        |      500 |
| Hatch Period (days)                        |       15 |
| Hatch Tribute (%)                          |        5 |
| Membership Ratio (wxDai/CSTK)            |       10 |
| Hatch Minting Rate (TECH/wxDai)           |    10000 |
| Support Required (%)                       |       60 |
| Minimum Quorum (%)                |        2 |
| Vote Duration (days)                       |        3 |
| Vote Proposal Buffer (hours)                        |        8 |
| Ragequit (hours)                          |        1 |
| Tollgate Fee (wxDai)                       |     1000 |

**Comment by GriffGreen** [comment]
Ok, had to remove spaces to make space!

https://docs.google.com/document/d/1ViRu34v5zX9kpOfL0xgHohc0BrOJikjLYlP3GIy5Pfs/edit?usp=sharing

**Comment by GriffGreen** [comment]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=100000&tgihr=150&maxihr=500&ihtr=2500000&ihmaxr=50000000&hor=10&hpd=15&her=10000&ht=5&sr=60&maq=2&vdd=3&vbh=8&rqh=1&tfx=1000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)


# Graphical Summary

![image](https://hcti.io/v1/image/91a16d0c-fd9b-4c78-90fa-07a66ba341cc)


## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.  
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.


# Simulated Outcomes

![image](https://hcti.io/v1/image/d977f1aa-202f-49a8-be07-086cedb22b31)


# Hatch Strategy

<p>We need to put lots of text here</p>
 

# DAO Strategy

<p>We should give them the space to explain their thoughts</p>

# Summary

 ## Hatch Details

- Trusted Seed members can send wxDai to the Hatch for 15 days.

- The target goal will be 2500000 wxDai, with a minimum of 100000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 50000000 wxDai.

- Backers will need to send in 0.0001 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

## DAO Details

- Proposals will be voted on for 3 days. They will require at least 60% support, and a minimum of 2% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 1 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=100000&tgihr=150&maxihr=500&ihtr=2500000&ihmaxr=50000000&hor=10&hpd=15&her=10000&ht=5&sr=60&maq=2&vdd=3&vbh=8&rqh=1&tfx=1000" target="_blank">here, just check out the Impact Hour Results table.

# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2500000|
|Maximum Goal (wxDai)|5000000|
|Minimum Goal (wxDai)|700000|
|Impact Hour Rate at Target Goal (wxDai/IH)|60|
|Impact Hour Rate at Infinity (wxDai/IH)|180|
|Hatch Membership Ratio (wxDai/CSTK)|10|
|Hatch Period (days)|15|
|Hatch Minting rate (TECH/wxDai)|10000|
|Hatch Tribute (%)|5|
|Support Required (%)|93 |
|Minimum Quorum (%)|2 |
|Vote Duration (days)|3 |
|Vote Buffer (hours)|8 |
|Ragequit (hours)|18 |
|Tollgate Fee (wxDai)|1000 |</a>
