### ISSUE TITLE
Confirm that every param is described by the outputs by documenting how each one is shown in the outputs

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#242]
the text for the outputs is showing all the ones that are not in the graphs... but are all of the included? 

- [ ] Target goal
- [ ] Min goal
- [ ] Max goal
- [ ] all the other params

**Comment by PabloCGL** [comment]
|Parameter								|Documented in:|
|:------------------------------------|---------:|
|Target raise (wxDai) 					|	The final param table, marked with the label "Target Raise"|
|Maximum raise (wxDai) 					|	The final param table,  marked with the label "Max Raise"|
|Minimum raise (wxDai) 					|	The final param table  marked, with the label "Min Raise"|
|Impact hour slope (wxDai/IH) 			|	Shown in the graphs. Also, several impact hour rates according to different amounts raised are shown in the final param table. |
|Maximum impact hour rate (wxDai/IH) 	|	In the final param table on the row with "Max Raise", but there seems to be an issue (see below) |
|Hatch oracle ratio (wxDai/CSTK) 		|	Mentioned in the results text block |
|Hatch period (days) 					|	NOT MENTIONED|
|Hatch exchange rate (TECH/wxDai) 		|	NOT MENTIONED   |
|Hatch tribute (%) 						|	Shown in the pie charts. Also mentioned in the final param table as absolute wxDai number |
|Support required (%) 					|	Shown in the graph|
|Minimum accepted quorum (%) 			|	Shown in the graph|
|Vote duration (days) 					|	Mentioned in the results text block|
|Vote buffer (hours) 					|	Mentioned in the results text block|
|Rage quit (hours) 						|	Mentioned in the results text block|
|Tollgate fee (wxDai) 					|	Mentioned in the results text block|

I've noticed that the Maximum Impact Hour Rate param and the actual highest impact hour rate on the table don't match. Is this intended behaviour? Also, after the row with the max raise there are several more filled with NaN.


I've rewritten the results box to account for the missing info and restructured it a bit to make key points more explicit. This way,
the first table becomes truly redundant as @divine-comedian said in issue #255. It would look like this: 



<h1>Results</h1>

<p>{comments}</p>

<h2> Hatch Parameters </h2>

- The Hatch will last {hatch_period_days}.

- The target amount to raise will be {ihf_target_raise}, with a minimum of {ihf_minimum_raise} necessary for the Hatch to succeed and a cap at {ifh_maximum_raise} .

- Every wxDai sent in by the backers will mint them {hatch_exchange_rate} TECH Tokens.

- The membership ratio is set at {hatch_oracle_ratio}. This way, a CSTK Token holder that has 2000 CSTK can send a max of {max_wxdai_ratio} wxDai to the Hatch.

- The maximum possible Impact Hour Rate will be {maximum_impact_hour_rate}, with the slope set to {hour_slope}. To see how the rate evolves relative to the amount of wxDai raised, check out the charts and scenarios below.


<h2> Dandelion Voting Parameters </h2>

- It will cost {tollgate_fee_xdai} wxDai to make a proposal.

- Proposals will be voted on for {vote_duration_days} days. They will require at least {support_required} % support, and will have to achieve a minimum quorum of {minimum_accepted_quorum} %.

- TECH token holders will have {rage_quit_hours} hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes).

- There will be a minimum of {vote_buffer_hours} hours between proposals so people always have time to exit safely.

- A proposal that passes can be executed {proposal_execution_hours} hours after it was proposed.



Play with my parameters [...]

**Comment by GriffGreen** [comment]
<h1>Hatch Configuration Explanation</h1>

<p>{comments}</p>

<h2> Hatch Parameters </h2>

- Trusted Seed members can send wxDai to the Hatch for {hatch_period_days} days.

- The target goal will be {ihf_target_raise} wxDai, with a minimum of {ihf_minimum_raise} wxDai necessary for the TEC Hatch DAO to be launched and a cap at {ifh_maximum_raise} wxDai.

- Backers will need to send in 1/{hatch_exchange_rate} wxDai to mint 1 TECH.

- The membership ratio is set at {hatch_oracle_ratio} wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to {max_wxdai_ratio*1125} wxDai to the Hatch.



<h2> TEC Hatch DAO Voting Parameters </h2>

- It will cost {tollgate_fee_xdai} wxDai to make a proposal. This can be refunded by a vote later.

- Proposals will be voted on for {vote_duration_days} days. They will require at least {support_required} % support, and a minimum of {minimum_accepted_quorum} % of the TECH Tokens will have to vote yes for a proposal to pass. 

- TECH token holders will have {rage_quit_hours} hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of {vote_buffer_hours} hours between proposals so people always have time to exit safely if they voted yes on a previous vote.

- A proposal that passes can be executed {proposal_execution_hours} hours after it was proposed.
