### ISSUE TITLE
Math isn't working on the CSTK ratio

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#270]
![Screen Shot 2021-04-30 at 3.49.32 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/8f775446-8bea-4e0c-ae5d-d1fe47732f97)

**Comment by GriffGreen** [comment]
this should be 10 x 1125 = 11250 wxdai not 12250 wxdai

**Comment by PabloCGL** [comment]
It's a typo on the interface side. I'll fix it right away.
