### ISSUE TITLE
Update your results doesn't update the comments section

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#286]
If you edit the Comments section you have to click run simulation above for the new text to be captured

![Screen Shot 2021-05-02 at 7.02.37 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/2fc4b5d2-6ff6-4787-ac77-0311514240d3)

The proposal generated has the old text

![Screen Shot 2021-05-02 at 7.04.08 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/b59e61c4-4be8-4fe2-b2a8-95ae2eafbc2f)

**Comment by marthendalnunes** [comment]
@GriffGreen actually the comments update, but it takes the time to process the results again (call API, render HTML to images, etc), which takes around 10 seconds. But I agree that is not the best UX when you just want to change the comments.

**Comment by GriffGreen** [comment]
Is there a way to make the submit to github button unclickable either until it is loaded or at least for a period of time to avoid this error?

**Comment by GriffGreen** [comment]
Fabio has a PR to disable submissions until it loads
