### ISSUE TITLE
Hatch Dashboard Redesign

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/Token-Log-Hatch-Params#77]
Summary notes from design sesh with Vitor, Fabio and Marko.

**Hatch Dashboard Design Sesh**

How much Frontend can be modified?

Easy to change grid, sliders etc, but chasing styles is tricky because it generates the object in Python which also generates HTML/CSS, that is harder to change.
Easy to change colours.
Easy to change layout, position of elements on the screen.

Sliders, do we have permissions to change the colours? Vitor will look into that.

Tooltips - out of option to be added.
We can make glossary which opens a popup or external link with explanation of each param. Also we can link to external resources to learn more about all the stuff happening in the background (the WHY).

Jeff’s issue to add text above each section - GOOD TO GO!
Include link to open popup for more explanation that was meant to be displayed in Tooltips for each param.

Disable user ability to reorder elements on the dashboard.

Import Params User Flow:

	1.	User A shares params on Github
	2.	User B clicks on link “play with my params”
	3.	Hatch Dashboard opens
	4.	onload function is called to check if there are params in URL
	5.	run IF statement to show either fresh page or imported params from GitHub
	6.	inform user IF importing params that they are being imported, inform when import is completed

Colors on Dandellion chart have a meaning.
Add legend for green (Yes votes) and red (No votes) and blue treshshold.
Try adding emoji thumb up/down for Yes/No votes.

Add big titles for each section and more padding between them.
1. Impact hours
2. Hatch
3. Dandellion voting

Add Introduction section at the top of the Dashboard (refer to the narrative).
https://forum.tecommons.org/t/launching-in-2-parts-first-hatch-dandelion-then-vote-to-add-abc-cv/85

**Next Steps:** Fabio and Vitor to create issues for this epic and start working on adjustments. Contact Marko if design help needed.

Resources:

Parameter Names https://docs.google.com/spreadsheets/d/1NBizA4mbj4iFuTkcfg3M1Q7v-9exhMcja8u2BshV5V8/edit#gid=0
Parameter Glossary https://docs.google.com/document/d/1rNE37FvYxkNSbIRvYXTQlOReJzXExUq_IDYv4Oem4NE/edit

**Comment by freedumbs00** [comment]
https://dash-gallery.plotly.host/dash-oil-and-gas/

Great new direction for the actual Dashboard for the Upgrades.    LOVE IT.   @marthendalnunes and @famole GREAT JOB
